apiVersion: apps/v1
kind: Deployment
metadata:
  name: quell-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-hw-md
  template:
    metadata:
      labels:
        app: flask-hw-md
    spec:
      containers:
      - name: flask-hw-md3
        image: ghcr.io/sweem2k/flask-hw-md3:latest
        ports:
        - containerPort: 3333

---
apiVersion: v1
kind: Service
metadata:
  name: flask-hw-md-service
spec:
  type: NodePort
  selector:
    app: flask-hw-md3
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
      nodePort: 30333